[package]
name = "rs-torrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
serde = {version = "1.0", default-features = false }
serde_bytes = "0.11"
serde_derive = "1.0"
itoa = "1.0.2"